---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-release-git-helm-towards5gs
  namespace: flux-system
spec:
  chart:
    spec:
      chart: charts/free5gc
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: source-git-helm-towards5gs-helm
  interval: 10s
  targetNamespace: test-5gs
