---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: source-git-helm-towards5gs-helm
  namespace: flux-system
spec:
  interval: 10s
  ref:
    branch: main
  url: https://github.com/Orange-OpenSource/towards5gs-helm
